require('settings')
require('packer-config')
-- require('colorschemes-config.nightfox')
require('colorschemes-config.nord')
require('nvim-tree-config')
require('mappings')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
